In [27]:
import numpy as np
import pandas as pd
import math
import time
import matplotlib.pyplot as plt

In [107]:
nac = pd.read_csv(r'csv_files/nac.csv')

In [109]:
length = len(nac)

In [112]:
tmc_df = pd.read_csv(r'csv_files/tmc_oth.csv')

In [121]:
tmc_rows_nac_cols = pd.DataFrame(index=range(855),columns=range(length))

In [122]:
from shapely.geometry import Point
from shapely.geometry.polygon import Polygon

count_intersects =0 
count_contains = 0
points =[[] for k in range(length)] 
truthvalue = [False,False,False,False]

for i in range(length):
    points[i]=[Point(nac1.iloc[:,2][i], nac1.iloc[:,3][i]), Point(nac1.iloc[:,4][i], nac1.iloc[:,5][i]), Point(nac1.iloc[:,6][i], nac1.iloc[:,7][i]), Point(nac1.iloc[:,8][i], nac1.iloc[:,9][i])]

polygons = []
for i in range(855):
    polygons.append(Polygon([(tmc_df_ahead['ul_la'][i], tmc_df_ahead['ul_lo'][i]), (tmc_df_ahead['ur_la'][i], tmc_df_ahead['ur_lo'][i]), (tmc_df_ahead['lr_la'][i], tmc_df_ahead['lr_lo'][i]), (tmc_df_ahead['ll_la'][i], tmc_df_ahead['ll_lo'][i])]))
for k in range(855):
    for i in range(length):
        for j in range(4):
            truthvalue[j] = polygons[k].contains(points[i][j])
        tmc_rows_nac_cols.iloc[k,i]="n"
        if(truthvalue[0]==True or truthvalue[1]==True or truthvalue[2]==True or truthvalue[3]==True):
            tmc_rows_nac_cols.iloc[k,i]="intersects"
            count_intersects+=1
        if(truthvalue[0]==True and truthvalue[1]==True and truthvalue[2]==True and truthvalue[3]==True):
            tmc_rows_nac_cols.iloc[k,i]="contains"
            count_contains+=1
            count_intersects-=1

In [123]:
tmc_rows_nac_cols

,0,1,2,3,4,5,6,7,8,9,...,14016,14017,14018,14019,14020,14021,14022,14023,14024,14025
0,n,n,n,n,n,n,n,n,n,n,...,n,n,n,n,n,n,n,n,n,n
1,n,n,n,n,n,n,n,n,n,n,...,n,n,n,n,n,n,n,n,n,n
2,n,n,n,n,n,n,n,n,n,n,...,n,n,n,n,n,n,n,n,n,n
3,n,n,n,n,n,n,n,n,n,n,...,n,n,n,n,n,n,n,n,n,n
4,n,n,n,n,n,n,n,n,n,n,...,n,n,n,n,n,n,n,n,n,n
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
850,n,n,n,n,n,n,n,n,n,n,...,n,n,n,n,n,n,n,n,n,n
851,n,n,n,n,n,n,n,n,n,n,...,n,n,n,n,n,n,n,n,n,n
852,n,n,n,n,n,n,n,n,n,n,...,n,n,n,n,n,n,n,n,n,n
853,n,n,n,n,n,n,n,n,n,n,...,n,n,n,n,n,n,n,n,n,n
854,n,n,n,n,n,n,n,n,n,n,...,n,n,n,n,n,n,n,n,n,n

In [124]:
tmc_rows_nac_cols.to_csv("csv_files/tmc_nac_intersections.csv")

In [125]:
count_contains

11940

In [126]:
count_intersects

5670

In [127]:
tmclist_intersects=[]
naclist_intersects=[]
tmclist_contains=[]
naclist_contains=[]

In [128]:
for i in range(855):
    for j in range(length):
        if(tmc_rows_nac_cols.iloc[i,j]=="intersects"):
            tmclist_intersects.append(i)
            naclist_intersects.append(j)
        if(tmc_rows_nac_cols.iloc[i,j]=="contains"):
            tmclist_contains.append(i)
            naclist_contains.append(j)

In [130]:

nacset_contains = set(naclist_contains)
tmcset_contains = set(tmclist_contains)

In [98]:
print(set(tmclist_contains+tmclist_intersects))

{352, 708, 709, 269, 557, 749, 766, 848, 179, 216, 441, 187, 318, 287}

In [ ]:
pd.DataFrame(index=range(count_contains))
tmc_nac_contains = pd.DataFrame(index= range(len(tmclist_contains)), columns = ['tmc','nac'])

In [135]:
for i in range(len(tmclist_contains)):
    tmc_nac_contains.tmc[i]=tmc_df.name[tmclist_contains[i]]
    tmc_nac_contains.nac[i]=nac.name[naclist_contains[i]]

In [139]:
tmc_nac_contains.to_csv("csv_files/tmc_nac_contains.csv")